services:
  business-db:
    restart: "no"
    ports:
      - "${POSTGRES_PORT_EXT?Variable not set}:${POSTGRES_PORT?Variable not set}"
    networks:
      - tpii-network

  business-service:
    restart: "no"
    ports:
      - "${SERVICE_PORT_EXT?Variable not set}:8000"
    build: .
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: .
          action: sync
          target: /app
          ignore:
            - .venv
        - path: ./pyproject.toml
          action: rebuild
    volumes:
      - ./htmlcov:/app/htmlcov
    labels:
      - "traefik.http.routers.businesses.rule=PathPrefix(`/api/v1/businesses`)"
      - "traefik.http.routers.courts.rule=PathPrefix(`/api/v1/padel-courts`)"
      - "traefik.http.routers.businesses.middlewares=cors,x-api-key@file,my-easy-traefik-rate-limit-jwt@file"
      - "traefik.http.routers.courts.middlewares=cors,x-api-key@file,my-easy-traefik-rate-limit-jwt@file"
    networks:
      - tpii-network

networks:
  tpii-network:
    external: true